version: "3.9"
services:
  app:
    container_name: bookings_api
    env_file:
      - .env
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    tty: true
    build: .
    ports:
      - 8000:8080
    restart: on-failure
    depends_on:
      - postgresdb
    networks:
      - spacetrouble

  postgresdb:
    image: postgres:14.5-bullseye
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '1234:5432'
    networks:
      - spacetrouble
    volumes:
      - /tmp/db_data:/var/lib/postgresql/data

networks:
  spacetrouble:
    driver: bridge